# Identify Yourself

In [1]:
# --- Cell 1: identify yourself ---

name = "Riodino Laihan"
student_id = "50261893"

print(name, student_id)

Riodino Laihan 50261893

# Q1 Load the Data

In [7]:
import pandas as pd

stock_url = "https://raw.githubusercontent.com/riodino14/colab-project/main/stockReturnDF2.csv"
shares_url = "https://raw.githubusercontent.com/riodino14/colab-project/main/ShareOutstanding.csv"

stockDF = pd.read_csv(stock_url)
shareOutDF = pd.read_csv(shares_url)

print("Stock DataFrame shape:", stockDF.shape)
print("Share Outstanding DataFrame shape:", shareOutDF.shape)

Stock DataFrame shape: (15099, 10)
Share Outstanding DataFrame shape: (3, 2)

In [8]:
# # --- Q1: Load the data ---

# import pandas as pd

# stockDF = pd.read_csv("stockReturnDF2.csv")
# shareOutDF = pd.read_csv("ShareOutstanding.csv")

# print("Stock DataFrame shape:", stockDF.shape)
# print("Share Outstanding DataFrame shape:", shareOutDF.shape)

## Q2. Look at the Data

The price data contains daily stock price information for each ticker.

In [ ]:
# Show the first 5 rows 
stockDF.head()

,date,open,high,low,close,adjusted close,volume,dividend amount,split coefficient,ticker
0,2019-10-31,168.51,168.56,163.55,164.99,164.99,2639274,0.0,1.0,MMM
1,2019-10-30,168.23,168.57,167.03,168.37,168.37,1780100,0.0,1.0,MMM
2,2019-10-29,168.03,169.95,167.51,168.81,168.81,2669200,0.0,1.0,MMM
3,2019-10-28,166.48,169.71,166.20,169.06,169.06,3137500,0.0,1.0,MMM
4,2019-10-25,162.51,167.63,162.13,166.09,166.09,3104700,0.0,1.0,MMM

In [11]:
# Show the last 5 Rows 
stockDF.tail()

,date,open,high,low,close,adjusted close,volume,dividend amount,split coefficient,ticker
15094,1999-11-05,37.875,38.875,37.8750,38.438,10.6687,13604600,0.0,1.0,ABT
15095,1999-11-04,37.438,38.250,37.0000,37.875,10.5125,15124600,0.0,1.0,ABT
15096,1999-11-03,37.750,38.250,36.8130,36.813,10.2176,19538700,0.0,1.0,ABT
15097,1999-11-02,39.063,39.625,37.5615,38.000,10.5472,22183400,0.0,1.0,ABT
15098,1999-11-01,40.500,41.125,40.0000,40.313,11.1891,8656500,0.0,1.0,ABT

One row represents the daily stock price and trading information for one ticker on one trading day.

# Q3. Columns

In [23]:
# Print the column names 
print("Column names: ")
print(stockDF.columns.tolist())
print("number of columns: ",len(stockDF.columns.tolist()))

# Count the unique tickers 
print("List of the unique tickers: ", stockDF["ticker"].unique())
print("Total number of the unique tickers ", len(stockDF["ticker"].unique()))
# print(stockDF["ticker"].nunique())

Column names:
['date', 'open', 'high', 'low', 'close', 'adjusted close', 'volume', 'dividend amount', 'split coefficient', 'ticker']
number of columns:  10
List of the unique tickers:  ['MMM' 'AOS' 'ABT']
Total number of the unique tickers  3

# Q4. Add a Column 
Add Dollar Volume. 
Dollar volume is calculated as:

dollarVolume = close × volume

In [25]:
stockDF["volume"] = stockDF["close"] * stockDF["volume"]

# show the first 5 rows 
stockDF["volume"].head()

0    4.354538e+08
1    2.997154e+08
2    4.505877e+08
3    5.304258e+08
4    5.156596e+08
Name: volume, dtype: float64